services:
  postgres:
    image: postgres:alpine
    container_name: sinergia_postgres
    ports:
      - "8950:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sinergia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    restart: always

volumes:
  postgres_data:
    name: sinergia_postgres_data

networks:
  default:
    name: sinergia_network