# ENV
env=qa

# FRONTEND
frontend.url=https://crm-qa.sinerg-ia.es

# SERVER
server.port=80

# SECURITY
security.jwt.secret=${SECURITY_JWT_SECRET}
security.jwt.cookie.secure=true
security.jwt.cookie.name=REFRESH_TOKEN_QA
security.jwt.cookie.domain=sinerg-ia.es
security.api.secret=${SECURITY_API_SECRET}

# DB
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update