# ENV
env=dev

# FRONTEND
frontend.url=https://localhost:8901

# SERVER
server.port=8900
server.ssl.key-store-type=PKCS12
server.ssl.key-store=${HOME}/.sinergia/ssl/localhost.p12
server.ssl.key-store-password=password
server.ssl.key-alias=localhost
server.ssl.enabled=true

# SECURITY
security.jwt.secret=DUMMYSECRET
security.jwt.cookie.secure=false
security.jwt.cookie.name=REFRESH_TOKEN_DEV
security.jwt.cookie.domain=localhost
security.api.secret=dF8ncX7SeV60DzEh6ygsDdBc56W4GO8W

# DB
spring.datasource.url=jdbc:postgresql://localhost:8950/sinergia
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true